FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# MyTrainy

API per usare la piattaforma MyTrainy, progetto di Ingengeria del Software UniTN 2022

## Registrazione [/api/v1/users]

### Registrazione di un nuovo utente POST
Due tipologie:
* atleta
* allenatore